version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
  api:
    container_name: naretiv-backend
    build:
      context: ./
      target: production
    image: naretiv-backend
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000
    env_file:
      - ./.env

    links:
      - postgres
      - redis
    volumes:
      - ./:/src
volumes:
  progresDB:
    driver: local
  redisDB:
    driver: local
